//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointCustomSystemDataMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOffices
    {
        public int Post_id { get; set; }
        public string PostalCode { get; set; }
        public string PostOffice { get; set; }
        public Nullable<int> Personnel_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> TreatmentOffice_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Studentx Studentx { get; set; }
        public virtual TreatmentOffice TreatmentOffice { get; set; }
    }
}
