CREATE TABLE [dbo].[Reservation] (
    [Reservation_id]       INT             IDENTITY (1, 1) NOT NULL,
    [Start]                DATETIME        NULL,
    [End]                  DATETIME        NULL,
    [Date]                 DATE            NULL,
    [TreatmentPaid]        BIT             NULL,
    [TreatmentPaidDate]    DATE            NULL,
    [Type]                 INT             NULL,
    [Note]                 NVARCHAR (300)  NULL,
    [CalendarTitle]        NVARCHAR (2000) NULL,
    [TreatmentReportTexts] NVARCHAR (3000) NULL,
    [TreatmentCompleted]   BIT             NULL,
    [Personnel_id]         INT             NULL,
    [Student_id]           INT             NULL,
    [Customer_id]          INT             NULL,
    [TreatmentPlace_id]    INT             NULL,
    [Treatment_id]         INT             NULL,
    [TreatmentOffice_id]   INT             NULL,
    [User_id]              INT             NULL,
    PRIMARY KEY CLUSTERED ([Reservation_id] ASC),
    CONSTRAINT [FK_Reservation_ToTable] FOREIGN KEY ([Personnel_id]) REFERENCES [dbo].[Personnel] ([Personnel_id]),
    CONSTRAINT [FK_Reservation_ToTable_1] FOREIGN KEY ([Student_id]) REFERENCES [dbo].[Studentx] ([Student_id]),
    CONSTRAINT [FK_Reservation_ToTable_3] FOREIGN KEY ([TreatmentPlace_id]) REFERENCES [dbo].[TreatmentPlace] ([TreatmentPlace_id]),
    CONSTRAINT [FK_Reservation_ToTable_4] FOREIGN KEY ([Treatment_id]) REFERENCES [dbo].[Treatment] ([Treatment_id]),
    CONSTRAINT [FK_Reservation_ToTable_5] FOREIGN KEY ([User_id]) REFERENCES [dbo].[User] ([User_id]),
    CONSTRAINT [FK_Reservation_ToTable_2] FOREIGN KEY ([Customer_id]) REFERENCES [dbo].[Customer] ([Customer_id]),
    CONSTRAINT [FK_Reservation_ToTable_6] FOREIGN KEY ([TreatmentOffice_id]) REFERENCES [dbo].[TreatmentOffice] ([TreatmentOffice_id])
);

